In [3]:
import torch
import torch.nn as nn

You should consider upgrading via the 'c:\users\nt930qcg\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


#### 01. 입력 벡터 Xt 생성

In [16]:
# Xt 벡터의 크기 설정
d = 4

# 무작위 값으로 1차원 벡터 초기화
xt = torch.randn(d)

# Xt 벡터 정보 확인
display(f"x_t 출력 결과 : {xt}")

# 벡터이기 때문에 1차원
display(f"xt 차원 : {xt.dim()}")

# 해당 벡터가 몇개의 특성을 갖고 있는가
display(f"xt 형태 : {xt.shape}")

'x_t 출력 결과 : tensor([ 1.1093,  0.7071, -1.2237,  1.5263])'

'xt 차원 : 1'

'xt 형태 : torch.Size([4])'

#### 02. 초기 은닉 상태 ht-1 설정

In [17]:
# 은닉 상태 벡터의 크기 설정
Dh = 6

# 이전 은닉 상태 벡터를 0값으로 초기화
ht1 = torch.zeros(1, Dh)

# ht1의 차원 확인
print(ht1.dim())

# ht1의 형태 확인
print(ht1.shape)

2
torch.Size([1, 6])


#### 03. 입력에 대한 가중치 Wx 설정

In [18]:
# 입력 가중치 행렬 설정
Wx = torch.randn(Dh, d)

# 입력 가중치 행렬 출력
display(Wx)

# 입력 가중치 행렬 차원
display(Wx.dim())

# 입력 가중치 행렬 형태
display(Wx.shape)

tensor([[-0.0670, -0.1276,  2.0441, -1.1606],
        [ 1.3907,  0.5164, -1.2823,  1.9930],
        [-0.6187, -0.6084,  1.6602,  0.5403],
        [-0.8841,  1.7086, -0.7395, -0.4605],
        [ 0.0140,  3.1740, -0.2384,  0.6277],
        [ 0.9870,  0.5122, -0.1796,  0.0432]])

2

torch.Size([6, 4])

#### 04. 은닉 상태에 대한 가중치 Wh 설정

In [19]:
# 은닉 상태 가중치 행렬 설정
Wh = torch.randn(Dh, Dh)

# 은닉 상태 가중치 행렬 확인
display(Wh)

# 은닉 상태 가중치 행렬 차원
display(Wh.dim())

# 은닉 상태 가중치 행렬 형태
display(Wh.shape)

tensor([[-0.8040, -0.5049,  0.9456,  0.6515,  0.3184,  0.9090],
        [-0.8128,  1.2438, -0.9688, -0.8695,  0.7063, -0.8125],
        [ 2.7683,  1.5637, -0.5418,  2.5716, -0.5109,  0.6296],
        [ 0.9147,  0.7532,  0.1847,  1.4484,  0.0666,  1.6903],
        [ 2.1347, -0.6140,  2.1180,  0.5268,  0.2085,  0.3815],
        [ 0.4650,  0.5643,  1.1932, -0.8375, -0.0298,  1.1384]])

2

torch.Size([6, 6])

#### 05. 편향 b 설정

In [20]:
# 편향 b 설정
b = torch.randn(Dh)

# 편향 벡터 확인
display(b)

# 편향 차원 확인
display(b.dim())

# 편향 형태 확인
display(b.shape)

tensor([-0.7060,  1.9480, -1.8572,  0.0187, -1.9432, -0.3462])

1

torch.Size([6])

#### 06. 현시점 은닉상태 계산

In [21]:
# 현재 은닉 상태 ht 구하는 공식 작성
h_t = torch.tanh(torch.matmul(xt.unsqueeze(0), Wx.t()) 
                 + torch.matmul(ht1, Wh.t()) 
                 + b.unsqueeze(0))

#### 07. 출력 가중치 Wy 및 출력 Yt 계산

In [22]:
# 출력 벡터의 차원 정의
Dy = 2 

# 출력 가중치
Wy = torch.randn(Dh, Dy)

# 최종 출력값
y_t = torch.sigmoid(torch.matmul(h_t, Wy))